version: '2'

services:
    tomcat:
        image: timsijstermans/springmdb:0.8
        ports:
            - "8080"
        network_mode: host
        depends_on:
        - mymysql
    mymysql:
        image: mysql
        ports:
            - "3306:3306"
        expose:
            - "3306"
        network_mode: host
        environment:
            - MYSQL_ROOT_PASSWORD=root
